### ISSUE TITLE
EB-012: Users should be able to create invoice/estimate for only their customers

### ISSUE THREAD

**Issue by ChibuezePaul** [amoz28/easybook#23]
Customers are created/tied to a user. A user should be allowed to perform operations on users created or tied to them

**Comment by ChibuezePaul** [comment]
This should be extended to other operations a user does on a customer. This is the only way we can truely ensure a multi-tenant system

**Comment by ChibuezePaul** [comment]
I've corrected the invoice/estimate bit of this bug

**Comment by amoz28** [comment]
This should be working as requested already, have you confirmed it is not working like this?

**Comment by ChibuezePaul** [comment]
i only ensured this for invoice/estimate
